AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Authenticator Lambda

Resources:
  ApiAuthenticatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Environment:
        Variables:
          DB_HOST: "3.250.106.184"
          DB_PORT: "3306"
          DB_USER: "tournament_user"
          DB_PASSWORD: "HX&jaa4%TK@wj7K5$eYg"
          DB_NAME: "tournament_db"
