AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to create riot accounts

Resources:
  ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Environment:
        Variables: 
          DB_HOST: "3.250.106.184"
          DB_PORT: "3306"
          DB_USER: "tournament_user"
          DB_PASSWORD: "HX&jaa4%TK@wj7K5$eYg"
          DB_NAME: "tournament_db"
          BUCKET_NAME: "lockout-tournament-assets"
          RIOT_API_KEY: "RGAPI-966cb6c9-0795-48b7-a4b1-72cddbf82fa8"