AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecretVersion:
    Type: String
  SecretArn:
    Type: String
  S3AssetsBucket:
    Type: String

Globals:
  Function:
    Runtime: python3.13
    Environment:
      Variables:
        SECRET_VERSION: !Ref SecretVersion
        DB_HOST: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:host}}"
        DB_PORT: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:port}}"
        DB_USER: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:user}}"
        DB_PASSWORD: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:password}}"
        DB_NAME: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:name}}"
        RIOT_API_KEY: !Sub "{{resolve:secretsmanager:${SecretArn}:SecretString:riot_api_key}}"
        BUCKET_NAME: !Ref S3AssetsBucket

Resources:
  ###########################################################
  # NESTED STACKS                                           #
  ###########################################################

  Schedules:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./scheduler.yaml
      Parameters:
        FetchChampionMasteryLambdaArn: !GetAtt FetchPlayerChampionMasteryLambda.Arn
        FetchMatchIDsLambdaArn: !GetAtt FetchMatchHistoryLambda.Arn
        FetchMatchDataLambdaArn: !GetAtt FetchMatchDataLambda.Arn
        FetchPlayerStatsLambdaArn: !GetAtt FetchPlayerStatsLambda.Arn
        ProcessMatchDataLambdaArn: !GetAtt ProcessMatchDataLambda.Arn

  ###########################################################
  # REST-API DEFINITION                                     #
  ###########################################################

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,OPTIONS,DELETE,POST,PATCH,PUT'"
        AllowOrigin: "'*'"
        AllowCredentials: false
      Auth:
        Authorizers:
            ApiTokenAuthorizer:
              FunctionArn: !GetAtt ApiAuthenticatorLambda.Arn
              FunctionPayloadType: REQUEST
              Identity:
                Headers:
                  - Authorization
                ReauthorizeEvery: 1
                
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: ApiTokenAuthorizer
      EndpointConfiguration:
        Type: REGIONAL

  LambdaWithS3AccessRole:
      Type: AWS::IAM::Role
      Properties:
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: S3BucketAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    - !Sub arn:aws:s3:::${S3AssetsBucket}
                    - !Sub arn:aws:s3:::${S3AssetsBucket}/*

  ApiAuthenticatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/api-authenticator/src/
      Handler: app.lambda_handler
      Timeout: 30

  ###########################################################
  # PLAYER LAMBDAS                                          #
  ###########################################################

  CreatePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/players/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: POST
            RestApiId: !Ref Api
  
  DeletePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/players/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: DELETE
            RestApiId: !Ref Api
  
  UpdatePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/players/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: PATCH
            RestApiId: !Ref Api

  ###########################################################
  # RESOURCE GET LAMBDA                                     #
  ###########################################################
  
  ResourceGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/resource-get/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpointPlayers:
          Type: Api
          Properties:
            Path: /players
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointPlayersSpecific:
          Type: Api
          Properties:
            Path: /players/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointTeams:
          Type: Api
          Properties:
            Path: /teams
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointTeamsSpecific:
          Type: Api
          Properties:
            Path: /teams/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointRiotAccounts:
          Type: Api
          Properties:
            Path: /riot-accounts
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointRiotAccountsSpecific:
          Type: Api
          Properties:
            Path: /riot-accounts/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointProfiles:
          Type: Api
          Properties:
            Path: /profiles
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointProfilesSpecific:
          Type: Api
          Properties:
            Path: /profiles/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointConfigs:
          Type: Api
          Properties:
            Path: /config
            Method: GET
            RestApiId: !Ref Api

  ###########################################################
  # RIOT ACCOUNT LAMBDAS                                    #
  ###########################################################

  CreateRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /riot-accounts
            Method: POST
            RestApiId: !Ref Api

  DeleteRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /riot-accounts
              Method: DELETE
              RestApiId: !Ref Api
  
  UpdateRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /riot-accounts
              Method: PATCH
              RestApiId: !Ref Api

  GetAccountsFromPlayerIdLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/player-get/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /riot-accounts/player/{player_id}
            Method: GET
            RestApiId: !Ref Api

  ###########################################################
  # TEAM LAMBDAS                                            #
  ###########################################################

  CreateTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/teams/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /teams
              Method: POST
              RestApiId: !Ref Api
  
  DeleteTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/teams/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /teams
              Method: DELETE
              RestApiId: !Ref Api
  
  UpdateTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/teams/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /teams
            Method: PATCH
            RestApiId: !Ref Api

  ###########################################################
  # MATCH HISTORY LAMBDAS                                   #
  ###########################################################

  FetchMatchHistoryLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/matches/get-match-ids/src/
      Handler: app.lambda_handler
      Timeout: 30
  
  FetchMatchDataLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/matches/get-match-data/src/
      Handler: app.lambda_handler
      Timeout: 30
  
  ProcessMatchDataLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/matches/process-match-data/src/
      Handler: app.lambda_handler
      Timeout: 60

  ###########################################################
  # LEAGUE STATS LAMBDAS                                    #
  ###########################################################

  FetchPlayerStatsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/player-stats/src/
      Handler: app.lambda_handler
      Timeout: 30

  ###########################################################
  # ACCOUNT CHAMPION MASTERY LAMBDAS                        #
  ###########################################################

  FetchPlayerChampionMasteryLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/champion-mastery/src/
      Handler: app.lambda_handler
      Timeout: 30

  ###########################################################
  # CONFIG LAMBDAS                                          #
  ###########################################################

  CreateOrUpdateConfigLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/config/create-update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /config
            Method: PUT
            RestApiId: !Ref Api
  
  DeleteConfigLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/config/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /config
              Method: DELETE
              RestApiId: !Ref Api

  ###########################################################
  # TOURNAMENT MATCH LAMBDAS                                #
  ###########################################################

  CreateTournamentMatchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/tournament-matches/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /tournament-matches
              Method: POST
              RestApiId: !Ref Api

  UpdateTournamentMatchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/tournament-matches/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /tournament-matches
              Method: PATCH
              RestApiId: !Ref Api

  DeleteTournamentMatchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/tournament-matches/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /tournament-matches
              Method: DELETE
              RestApiId: !Ref Api