AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DbSecretArn:
    Type: String
  S3AssetsBucket:
    Type: String

Resources:
  ###########################################################
  # REST-API DEFINITION                                     #
  ###########################################################

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,OPTIONS,DELETE,POST,PATCH'"
        AllowOrigin: "'*'"
        AllowCredentials: false
      Auth:
        Authorizers:
            ApiTokenAuthorizer:
              FunctionArn: !GetAtt ApiAuthenticatorLambda.Arn
              FunctionPayloadType: REQUEST
              Identity:
                Headers:
                  - Authorization
                ReauthorizeEvery: 1
                
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: ApiTokenAuthorizer
      EndpointConfiguration:
        Type: REGIONAL

  LambdaWithS3AccessRole:
      Type: AWS::IAM::Role
      Properties:
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: S3BucketAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    - !Sub arn:aws:s3:::${S3AssetsBucket}
                    - !Sub arn:aws:s3:::${S3AssetsBucket}/*

  ApiAuthenticatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/api-authenticator/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"

  ###########################################################
  # PLAYER LAMBDAS                                          #
  ###########################################################

  CreatePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/players/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: POST
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          BUCKET_NAME: !Ref S3AssetsBucket
  
  DeletePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/players/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: DELETE
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
  
  UpdatePlayerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/players/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /players
            Method: PATCH
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          BUCKET_NAME: !Ref S3AssetsBucket

  ###########################################################
  # RESOURCE GET LAMBDA                                     #
  ###########################################################
  
  ResourceGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/resource-get/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpointPlayers:
          Type: Api
          Properties:
            Path: /players
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointPlayersSpecific:
          Type: Api
          Properties:
            Path: /players/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointTeams:
          Type: Api
          Properties:
            Path: /teams
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointTeamsSpecific:
          Type: Api
          Properties:
            Path: /teams/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointRiotAccounts:
          Type: Api
          Properties:
            Path: /riot-accounts
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointRiotAccountsSpecific:
          Type: Api
          Properties:
            Path: /riot-accounts/{id}
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointProfiles:
          Type: Api
          Properties:
            Path: /profiles
            Method: GET
            RestApiId: !Ref Api
        ApiEndpointProfilesSpecific:
          Type: Api
          Properties:
            Path: /profiles/{id}
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables: 
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"

  ###########################################################
  # RIOT ACCOUNT LAMBDAS                                    #
  ###########################################################

  CreateRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /riot-accounts
            Method: POST
            RestApiId: !Ref Api
      Environment:
        Variables: 
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          RIOT_API_KEY: "RGAPI-966cb6c9-0795-48b7-a4b1-72cddbf82fa8"

  DeleteRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /riot-accounts
              Method: DELETE
              RestApiId: !Ref Api
      Environment:
        Variables: 
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
  
  UpdateRiotAccountLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /riot-accounts
              Method: PATCH
              RestApiId: !Ref Api
      Environment:
        Variables: 
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"

  GetAccountsFromPlayerIdLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/riot-accounts/player-get/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /riot-accounts/player/{player_id}
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"

  ###########################################################
  # TEAM LAMBDAS                                            #
  ###########################################################

  CreateTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/teams/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /teams
              Method: POST
              RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          BUCKET_NAME: !Ref S3AssetsBucket
  
  DeleteTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/teams/delete/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /teams
              Method: DELETE
              RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          BUCKET_NAME: !Ref S3AssetsBucket
  
  UpdateTeamLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/teams/update/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /teams
            Method: PATCH
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          BUCKET_NAME: !Ref S3AssetsBucket

  ###########################################################
  # MATCH HISTORY LAMBDA                                   #
  ###########################################################

  FetchMatchHistoryLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/match-history/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
            Type: Api
            Properties:
              Path: /match-history
              Method: POST
              RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"
          RIOT_API_KEY: "RGAPI-966cb6c9-0795-48b7-a4b1-72cddbf82fa8"
          
  ###########################################################
  # CONFIG LAMBDAS                                          #
  ###########################################################

  CreateConfigLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaWithS3AccessRole.Arn
      CodeUri: lambdas/config/create/src/
      Handler: app.lambda_handler
      Timeout: 30
      Runtime: python3.13
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /config
            Method: POST
            RestApiId: !Ref Api
      Environment:
        Variables:
          DB_HOST: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:host}}"
          DB_PORT: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:port}}"
          DB_USER: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:user}}"
          DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
          DB_NAME: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:name}}"